NODE ?= node
NPM  ?= npm

index.html: node_modules src/* src/db.json
	@${NODE} src/build.js

# command to rebuild db.json, will be executed
# only once if src/db.json isn't present
src/db.json:
	@${NODE} --harmony src/make-db.js

# `make db` will force rebuilding db.json even if it exists
db:
	@${MAKE} --always-make src/db.json

# removes autogenerated files
clean:
	rm src/db.json index.html

# install all packages if they don't exist (repo just been cloned)
node_modules: package.json
	@${NPM} install .

help:
	@echo 'make       - make index.html'
	@echo 'make db    - download stuff from other servers'
	@echo 'make clean - remove autogenerated files'
	@echo 'make help  - print this message (try that again)'

.PHONY: db clean help

